# based on PMOD retrieval

http://localhost:8888/lab/workspaces/surfrad_mfrsr_raw2netcdf/tree/projects/cmpaign_2025_PMOD/calibrate_cosine.ipynb

# execute the script

In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [7]:
import surfradpy.scripts.surfrad_mfrsr_cosinecalibration as srfcs

In [8]:
reload(srfcs)

In [16]:
out = srfcs.run(prefix= '/Volumes',
                log_folder= None,
                test = 1, 
                verbose = True)

start surfrad_mfrsr_cosinecalibration
start time: 2026-06-16 12:40:37.288775
inl
-----
blaasds
{'p2fld_in': '/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.netcdf/v0.4/', 'p2fld_out': '/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosine_corrected/v{version}/', 'date_from_name': <function run.<locals>.<lambda> at 0x3577e1120>, 'output_file_format': 'inl_mfrsr_cosinecorrected_{date}.nc', 'start': Timestamp('2026-04-17 12:40:37.288794'), 'end': Timestamp('2026-06-16 12:40:37.288794'), 'prefix': '/Volumes', 'reporter': <productomator.lab.Reporter object at 0x30eb16140>, 'verbose': True}
========
Get all files in /Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.netcdf/v0.4 with "files_between" function and start: 2026-04-17 12:40:37.288794, end: 2026-06-16 12:40:37.288794 and glob pattern: *.nc
inl workplan.shape: (22, 2)
number of cleanes: 0
number of errors: 0
number of warnings: 0
time finished: 2026-06-16 12:40:37.464909
total processing time: 4.892611111111111e-05 hours
No log file specified, skipping logging.

In [17]:
ci = out['product_instance']

In [18]:
ci.masterplan

,p2f_in,p2f_out
2026-04-17,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-18,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-19,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-20,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-21,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-22,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-23,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-24,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-25,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-26,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-27,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-28,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-29,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-04-30,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-01,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-02,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-03,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-04,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-05,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-06,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-07,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-08,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-09,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-10,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-11,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-12,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-13,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-14,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-15,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-16,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-17,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-18,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-19,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-20,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-21,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-22,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-23,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-24,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-25,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-26,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-27,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-28,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-29,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-30,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-31,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-01,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-02,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-03,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-05,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-06,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-07,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-08,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-09,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-10,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-11,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-12,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-13,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-14,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-15,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-16,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...

In [20]:
ci.workplan

,p2f_in,p2f_out
2026-05-25,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-26,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-27,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-28,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-29,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-30,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-05-31,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-01,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-02,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-03,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-05,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-06,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-07,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-08,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-09,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-10,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-11,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-12,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-13,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-14,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-15,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...
2026-06-16,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/raw.n...,/Volumes/grad/Inst/MFR/SURFRAD/inl/mfrsr/cosin...

# Calibrate files

In [1]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.cal_facility.lab as atmcal

In [2]:
import surfradpy.scripts.surfrad_mfrsr_cosinecalibration as srfccc
import productomator.worker as prowork

In [3]:
# colrenames = {'4155': np.int64(1625), '500': np.int64(500), '1625': np.int64(1625), '670': np.int64(670), '870': np.int64(870), '940': np.int64(940)}

# if np.any(np.array([abs(float(k)-v) for k,v in colrenames.items()]) > 20):
#     txt = f'''I believe there is a parsing error in the channels. Channels are parsed with Current matching table:
#     {colrenames}
#     '''
#     raise ValueError(txt)

In [4]:
reload(srfccc)
reload(srfccc.prolab)
reload(srfccc.srfcc)
reload(srfccc.srfcc.pm)
reload(srfccc.srfcc.pm.worker)
reload(srfccc.srfcc.atmspc)
reload(srfccc.srfcc.atmspc.atmcal)

AttributeError: module 'surfradpy.scripts.surfrad_mfrsr_cosinecalibration' has no attribute 'prolab'

In [ ]:
srfccc.srfcc.atmspc.atmcal.read_factory_cal_sol

In [ ]:
ci = srfccc.run(
    prefix='Volumes',
    log_folder=None,#'/home/grad/htelg/.processlogs/',
    start=None,
    end=None,
    noofdays=3,
    test=False,
    verbose=True,
    raise_errors=True
)

In [ ]:
ci.verbose

In [ ]:
pd.rea/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0672/Reported/V0672_20160605.spr

In [ ]:
'/Volumes/grad/Inst/MFR/SURFRAD/bnd/mfrsr/cosine_corrected/v0.1/2026/bnd_mfrsr_cosinecorrected_20260411.nc'

In [ ]:
Angle	Cos	NS_Corr_Thermopile	NS_Corr_415nm	NS_Corr_500nm	NS_Corr_1625nm	NS_Corr_670nm	NS_Corr_870nm	NS_Corr_940nm	NS_RelStdDv_Thermopile	NS_RelStdDv_415nm	NS_RelStdDv_500nm	NS_RelStdDv_1625nm	NS_RelStdDv_670nm	NS_RelStdDv_870nm	NS_RelStdDv_940nm

In [ ]:
import productomator as pm

In [ ]:
import sol_parser

In [ ]:
plt.rcParams['figure.dpi'] = 200

In [ ]:
reload(pm)
reload(pm.worker)

# This issue, when i apply my cosine it looks different

In [ ]:
import productomator as pm

In [ ]:
import atmPy.radiation.instrumentation.spectral as atmspc

In [ ]:
reload(pm)
reload(pm.worker)

In [ ]:
import surfradpy.products.mfrsr_cosinecorrection as srfcc

In [ ]:
reload(srfcc)
reload(srfcc.atmspc)
reload(srfcc.pm)
reload(srfcc.pm.worker)

In [ ]:
prefix = 'Volumes'
version_in = '0.3'
version_out = '0.1'
site = 'tbl'
p2fld_in = f'/{prefix}/grad/Inst/MFR/SURFRAD/{site}/mfrsr/raw.netcdf/v{version_in}/'
p2fld_out = f'/{prefix}/grad/Inst/MFR/SURFRAD/{site}/mfrsr/cosine_corrected/v{version_out}/'
#
prefix_h = 'Volumes/grad-1'
# p2fcal_sol = pl.Path(f'/{prefix_h}/mfrsr/Calinfo/SOL')
# p2fcal = pl.Path(f'/{prefix}/grad/Calibration_facilities/cucf/Surfrad/working')
#
p2cal_cos = 'V0660_20221109.cos'
p2cal_spr = 'V0660_20221103.spr'

cal = srfcc.CalibrateMFRSR(p2fld_in, 
                   p2fld_out,
                   output_file_format = f'{{year}}/{site}_mfrsr_cosinecorrected_{{date}}.nc',
                  date_from_name = lambda name: pd.to_datetime(name.split('_')[-1].replace('.nc', '')),
                  start = '2026-01-01',
                  end = '2026-04-10',
                   verbose = True,
                   # site = site,
                  )

# cal.workplan

In [ ]:
cal.workplan.iloc[0].p2f_out

In [ ]:
'{bla}'.format(bla = 'sdf', blub = 'asdfsadf')

In [ ]:
out = cal.process_row(iloc = 14, save=False)

In [ ]:
cal.workplan.iloc[0].p2f_out

In [ ]:
ds = out

In [ ]:
ds

In [ ]:
[v for v in ds]

In [ ]:
reorg = ['global_horizontal',
         'direct_normal',
         'diffuse_horizontal',
         'channel_wavelength',
         'cosine_calibraion_direct',
         'cosine_calibration_diffuse',
         'solar_zenith_angle',
         'solar_azimuth_angle',
         # 'airmass',
         # 'sun_earth_distance',
        ]

ds = ds[reorg]

In [ ]:
ds

In [ ]:
ds_raw

In [ ]:
cal.__class__.__name__

In [ ]:
self = cal

In [ ]:
f"{self.__class__.__module__}.{self.__class__.__qualname__}"

In [ ]:
class CalibrateMFR(pm.worker.Workplanner):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        
    def process_row(self, row = None, iloc = None, loc = None):
        """This is the method that does the particular work and will need to be overwritten in your subclass.
        Typical components:
        1. read the input file(s) (row.p2f_in)
        3. convert to xarray dataset (if needed)
        2. format the netcdf file
            2.1 add dataset attributes, creation datetime, creation software, server, site details, etc.
            2.2 add variable attributes, units, long_name, standard_name, etc.
        3. save the output file (row.p2f_out)
        
        Parameters
        ----------
        row : pandas.Series, optional
            A row from the workplan dataframe. This is how the process method callse this function.
        iloc : int, optional
            An integer index to select a row from the workplan dataframe.
        loc : index label, optional
            select a row by timestamp.
            """
        
        if iloc is not None:
            row = self.workplan.iloc[iloc]
        elif loc is not None:
            row = self.workplan.loc[loc]
        self.tp_row = row

        #####
        # get last processed instance - usefull if processing depends on the previous day
        ######
        # lastrow = self.get_last_row_before_workplan()
        # if isinstance(lastrow, type(None)):
        #     assert(False), 'set defaults?'
        # dslast = xr.open_dataset(lastrow.p2f_out)

        #######
        ## Open input files
        #######
        ds = xr.open_dataset(row.p2f_in)
        ds.attrs['site_latitude'] = ds.attrs['latitude']
        ds.attrs['site_longitude'] = ds.attrs['longitude']
        ds.attrs['site_elevation'] = ds.attrs['elevation']
        ds_raw = ds
        # si_raw = atmspc.atmsi.CombinedGlobalDiffuseDirect(ds)
        
        ## Do some processing here, e.g. add attributes, format the dataset, etc.
        # get last calibration files

        p2fld_cal = pl.Path(f'/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0{ds_raw.sn_mfrsr}/Reported/')
        assert(p2fld_cal.is_dir()), f'Folder containing calibration files, {p2fld_cal}, does not exist.'
        
        # get the .cos and .spr file with the closest date prior to the currently processed file
        def get_calfile(caltype = 'cos'):
            cosfiles = list(p2fld_cal.glob(f'*.{caltype}'))
            if len(cosfiles) == 0:
                raise ValueError(f'No .{caltype} files found in {p2fld_cal}')
        
            cosdates = [pd.to_datetime(c.name.split('_')[-1].split('.')[0]) for c in cosfiles]
            df = pd.DataFrame({'cosfile': cosfiles}, index = cosdates) 
            df.sort_index(inplace = True)
            df = df.truncate(after = row.name)
            if df.shape[0] == 0:
                raise ValueError(f'No .{caltype} files found in {p2fld_cal} with date prior to {row.name}\n{df}')
            p2fcos = df.cosfile.iloc[-1]
            return p2fcos
        
        p2fcos = get_calfile('cos')
        p2fspr = get_calfile('spr')

        # create instrument instance
        instrument = atmspc.Mfrsr(
                                spectral_calibration = p2fspr,
                                logger_calibration = None, # note needed, we are not doing absolute calibration, meaning consant cal-facotors will be corrected in the langley calibration step
                                head_calibration = None , # note needed, we are not doing absolute calibration, meaning consant cal-facotors will be corrected in the langley calibration step
                                cosine_responds = ds_cosine
                                )

        # pass raw data for calibration
        dscc = instrument.raw2calibrated(si_raw.dataset)
        ds = dscc.dataset
        dropvars = ['zenith_geometric']
        ds.drop_vars(dropvars)
        #########
        # Format the dataset attributes
        #########
        dropattrs = [
                    # '','','','','',
                    ]
        for a in dropattrs:
            ds.attrs.pop(a)

        ds.attrs['input_files'] = row.p2f_in
        ds.attrs['processing_date'] = pd.Timestamp.now().isoformat()
        ds.attrs['processing_server'] = socket.gethostname()
        
        ## Save the output file
        ds.to_netcdf(row.p2f_out)
        ds.close()
        return ds

In [ ]:
ds = dscc.dataset
ds

In [ ]:
ds.solar_azimuth_angle.att

In [ ]:
si_raw = atmspc.atmsi.CombinedGlobalDiffuseDirect(ds_raw)

p2fld_cal = pl.Path(f'/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0{ds.sn_mfrsr}/Reported/')
assert(p2fld_cal.is_dir()), f'Folder containing calibration files, {p2fld_cal}, does not exist.'

# get the .cos and .spr file with the closest date prior to the currently processed file
def get_calfile(type = 'cos'):
    cosfiles = list(p2fld_cal.glob(f'*.{type}'))
    if len(cosfiles) == 0:
        raise ValueError(f'No .{type} files found in {p2fld_cal}')

    cosdates = [pd.to_datetime(c.name.split('_')[-1].split('.')[0]) for c in cosfiles]
    df = pd.DataFrame({'cosfile': cosfiles}, index = cosdates) 
    df.sort_index(inplace = True)
    df = df.truncate(after = row.name)
    if df.shape[0] == 0:
        raise ValueError(f'No .{type} files found in {p2fld_cal} with date prior to {row.name}\n{df}')
    p2fcos = df.cosfile.iloc[-1]
    return p2fcos

p2fcos = get_calfile('cos')
p2fspr = get_calfile('spr')

In [ ]:
ds = ds_raw

In [ ]:
i = 14
# i += 1
print(i)
row = cal.workplan.iloc[i]
ds_raw = xr.open_dataset(row.p2f_in)
ds = ds_raw
ds.attrs['site_latitude'] = ds.attrs['latitude']
ds.attrs['site_longitude'] = ds.attrs['longitude']
ds.attrs['site_elevation'] = ds.attrs['elevation']


ch = 2
ds.global_horizontal.sel(channel = ch).plot()
ds.diffuse_horizontal.sel(channel = ch).plot()
print(row.p2f_in)

In [ ]:
p2fcos

In [ ]:
reload(atmspc)
reload(atmspc.atmsol)

In [ ]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.cal_facility.lab as atmcal

In [ ]:
p2fcos = pl.Path('/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0660/Reported/V0660_20221109.cos')
p2fcos = pl.Path('/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0660/Reported/V0660_20240208.cos')

print(p2fcos)
ds_cosine = atmcal.read_mfrsr_cal_cos(p2fcos, reversed_EW=False, reversed_NS=False)

In [ ]:
reload(atmcal)
reload(atmspc)

In [ ]:
instument = atmspc.Mfrsr(
                        spectral_calibration = p2fspr,
                        logger_calibration = None, # note needed, we are not doing absolute calibration
                        head_calibration = None , # note needed, we are not doing absolute calibration
                        cosine_responds = ds_cosine
                        )

In [ ]:
dscc = instument.raw2calibrated(ds_raw)

In [ ]:
dscc

In [ ]:
ds_raw

In [ ]:
import scipy.integrate as spi

In [ ]:
# add -90 and 90 if not present
# This is only so the integration goes all the way to pi/2 which impoves the normailiztion. The exact values at those angles should be irrelevant as cosine goes to zero, just infinit could be problementatic
ds = instument.cosine_responds.copy()

if -90 not in ds.Angle:
    dsother = ds.sel(Angle = -89)
    dsother.Angle.data = -90
    ds = xr.concat([dsother,ds], 'Angle')
if 90 not in ds.Angle:
    dsother = ds.sel(Angle = 89)
    dsother.Angle.data = 90
    ds = xr.concat([ds, dsother], 'Angle')

# do the integration
ang = np.deg2rad(ds.Angle).data
norm = spi.simpson(np.cos(ang), ang)
toll = 1e-8
test = abs(norm - 2)
assert(test < toll), f'Integral over the cos(angle) is expected to be close to 2. It is {norm}, which is larger than the tolerance of {toll}. Check for problems in the cosine responds data or increase tollerance (if you are really sure)'

# da = ds.spectral_NS
resNS = spi.simpson(ds.spectral_NS * np.cos(ang), ang)/norm
resEW = spi.simpson(ds.spectral_EW * np.cos(ang), ang)/norm
res = (resNS + resEW)/2

ds['spectral_diffuse'] = ('channel', res)

resNS = spi.simpson(ds.broadband_NS * np.cos(ang), ang)/norm
resEW = spi.simpson(ds.broadband_EW * np.cos(ang), ang)/norm

res = (resNS + resEW)/2

ds['broadband_diffuse'] = res

# cosine correction comparison

## what cosine correction was applied?

In [ ]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.surfrad.surfrad as atmsrf

In [ ]:
instument.cosine_calibration_diffuse

In [ ]:
1/ds.spectral_diffuse

In [ ]:
# si_tu = atmsrf.read_ccc(pl.Path('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/tu/2026/tbl_mfrsr_20260106_D824_3126_660.tu'), raisefilterfunctionerror=False)
si_tu = atmsrf.read_ccc(pl.Path('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/tu/2026/tbl_mfrsr_20260115_D824_3126_660.tu'), raisefilterfunctionerror=False)

si_tu.dataset = si_tu.dataset.reindex(datetime = ds_raw.datetime, method='bfill')
si_tu.dataset = si_tu.dataset.rename({'direct_normal_irradiation': 'direct_normal', 'diffuse_horizontal_irradiation': 'diffuse_horizontal', 'global_horizontal_irradiation': 'global_horizontal'})

In [ ]:
ch = 2
wl = 500
f,aa = plt.subplots(3, sharex = True, gridspec_kw={'hspace':0})
f.set_figheight(f.get_figheight() * 2)
what = 'global_horizontal'
# what = 'direct_normal'
# what = 'diffuse_horizontal'
a = aa[0]

dscc.dataset[what]
# ds_raw[what]
(dscc.dataset[what].sel(channel = wl) / si_raw.direct_normal_irradiation.dataset[what].sel(channel = ch)).plot(ax = a, label = 'cc/raw', zorder = 10)
(si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'tu/raw')
# (1/out.sel(channel = wl)).plot(ax = a)
dscc.dataset.cosine_calibraion_direct.sel(channel = wl).plot(ax = a, label = 'cc')

a.legend()
a.set_ylim(0.99, 1.2)

a = aa[2]
np.rad2deg(dscc.sun_position.zenith).plot(ax = a, label = 'zenith')
np.rad2deg(dscc.sun_position.azimuth).plot(ax = a, label = 'azimuth')

si_tu.dataset.solar_azimuth.plot()
si_tu.dataset.solar_zenith.plot()
a.set_ylim(50, 100)

a = aa[1]
((dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)) / (si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch))).plot(ax = a, label = 'tu/raw', ls = '', marker = '.', markersize = 0.5)
a.set_ylim(0.98, 1.02)
a.set_xlim(np.float64(20468.6), np.float64(20469.0))

for a in aa:
    a.grid(True)

In [ ]:
ch = 2
wl = 500
f,aa = plt.subplots(3, sharex = True, gridspec_kw={'hspace':0})
f.set_figheight(f.get_figheight() * 2)
what = 'global_horizontal'
what = 'direct_normal'
# what = 'diffuse_horizontal'
a = aa[0]

dscc.dataset[what]
# ds_raw[what]
(dscc.dataset[what].sel(channel = wl) / si_raw.direct_normal_irradiation.dataset[what].sel(channel = ch)).plot(ax = a, label = 'cc/raw', zorder = 10)
(si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'tu/raw')
# (1/out.sel(channel = wl)).plot(ax = a)
dscc.dataset.cosine_calibraion_direct.sel(channel = wl).plot(ax = a, label = 'cc')

a.legend()
a.set_ylim(0.99, 1.2)

a = aa[2]
np.rad2deg(dscc.sun_position.zenith).plot(ax = a, label = 'zenith')
np.rad2deg(dscc.sun_position.azimuth).plot(ax = a, label = 'azimuth')

si_tu.dataset.solar_azimuth.plot()
si_tu.dataset.solar_zenith.plot()
a.set_ylim(50, 100)

a = aa[1]
((dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)) / (si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch))).plot(ax = a, label = 'tu/raw', ls = '', marker = '.', markersize = 0.5)
a.set_ylim(0.98, 1.02)
a.set_xlim(np.float64(20468.6), np.float64(20469.0))

for a in aa:
    a.grid(True)

In [ ]:
ch = 1
wl = 415
f,aa = plt.subplots(3, sharex = True, gridspec_kw={'hspace':0})
f.set_figheight(f.get_figheight() * 1.5)
what = 'global_horizontal'
what = 'direct_normal'
# what = 'diffuse_horizontal'
a = aa[0]
(dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'cc/raw', zorder = 10)
(si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'tu/raw')
# (1/out.sel(channel = wl)).plot(ax = a)
# dscc.dataset.cosine_calibraion_direct.sel(channel = wl).plot(ax = a, label = 'cc')

a.legend()
a.set_ylim(0.99, 1.2)
a.grid(True)

a = aa[2]
np.rad2deg(dscc.sun_position.zenith).plot(ax = a, label = 'zenith')
np.rad2deg(dscc.sun_position.azimuth).plot(ax = a, label = 'azimuth')

si_tu.dataset.solar_azimuth.plot()
si_tu.dataset.solar_zenith.plot()

a = aa[1]
((dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)) / (si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch))).plot(ax = a, label = 'tu/raw', ls = '', marker = '.', markersize = 0.5)
a.set_ylim(0.98, 1.02)

a.set_xlim(np.float64(20468.5), np.float64(20469.049756944445))

In [ ]:
ch = 2
wl = 500
f,aa = plt.subplots(3, sharex = True, gridspec_kw={'hspace':0})
f.set_figheight(f.get_figheight() * 1.5)
what = 'global_horizontal'
what = 'direct_normal'
what = 'diffuse_horizontal'
a = aa[0]
(dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'cc/raw', zorder = 10)
(si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)).plot(ax = a, label = 'tu/raw')
# (1/out.sel(channel = wl)).plot(ax = a)
# dscc.dataset.cosine_calibraion_direct.sel(channel = wl).plot(ax = a, label = 'cc')

a.legend()
a.set_ylim(0.9, 1.2)
a.grid(True)

a = aa[2]
np.rad2deg(dscc.sun_position.zenith).plot(ax = a, label = 'zenith')
np.rad2deg(dscc.sun_position.azimuth).plot(ax = a, label = 'azimuth')

si_tu.dataset.solar_azimuth.plot()
si_tu.dataset.solar_zenith.plot()

a = aa[1]
((dscc.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch)) / (si_tu.dataset[what].sel(channel = wl) / ds_raw[what].sel(channel = ch))).plot(ax = a, label = 'tu/raw', ls = '', marker = '.', markersize = 0.5)
a.set_ylim(0.98, 1.12)

a.set_xlim(np.float64(20468.5), np.float64(20469.049756944445))

In [ ]:
ch = 2
wl = 500
f,a = plt.subplots()
ds_raw.global_horizontal.sel(channel = ch).plot(ax = a, label = 'raw')
dscc.dataset.global_horizontal.sel(channel = wl).plot(ax = a, label = 'cc')
si_tu.dataset.global_horizontal.sel(channel = wl).plot(ax = a, label = 'tu')


a.legend()

In [ ]:
amr = [2.2,4]

In [ ]:
si_raw.direct_normal_irradiation._am = None
si_raw.direct_normal_irradiation._pm = None
si_raw.direct_normal_irradiation.settings_langley_airmass_limits = amr

In [ ]:
dscc.direct_normal_irradiation._am = None
dscc.direct_normal_irradiation._pm = None
dscc.direct_normal_irradiation.settings_langley_airmass_limits = amr

In [ ]:
si_tu.direct_normal_irradiation._am = None
si_tu.direct_normal_irradiation._pm = None
si_tu.direct_normal_irradiation.settings_langley_airmass_limits = amr

## am

In [ ]:

si_raw.direct_normal_irradiation.langley_am.plot(wavelength=5, show_pre_clean=False)

In [ ]:
dscc.direct_normal_irradiation.langley_am.plot(wavelength=500, show_pre_clean=False)

In [ ]:
dscc.direct_normal_irradiation.langley_am.plot(wavelength=870, show_pre_clean=False)

In [ ]:
si_tu.direct_normal_irradiation.langley_am.plot(wavelength=500, show_pre_clean=False)

In [ ]:
si_tu.direct_normal_irradiation.langley_am.plot(wavelength=870, show_pre_clean=False)

## pm

In [ ]:
si_raw.direct_normal_irradiation.langley_pm.plot(wavelength=2, show_pre_clean=False)

In [ ]:
dscc.direct_normal_irradiation.langley_pm.plot(wavelength=500, show_pre_clean=False)

In [ ]:
dscc.direct_normal_irradiation.langley_pm.plot(wavelength=870, show_pre_clean=False)

In [ ]:
si_tu.direct_normal_irradiation.langley_pm.plot(wavelength=500, show_pre_clean=False)

In [ ]:
si_tu.direct_normal_irradiation.langley_pm.plot(wavelength=870, show_pre_clean=False)

In [ ]:
df = pd.DataFrame()
df['dscc_am'] = dscc.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['tu_am'] = si_tu.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['dscc_pm'] = dscc.direct_normal_irradiation.langley_pm.langley_fitres.intercept
df['tu_pm'] = si_tu.direct_normal_irradiation.langley_pm.langley_fitres.intercept

# df['tu_ratio'] = df.tu_am/df.tu_pm
# df['tu_dif'] = df.tu_am - df.tu_pm
# df['dscc_dif'] = df.dscc_am - df.dscc_pm

df['tu_dif'] = np.exp(df.tu_am) - np.exp(df.tu_pm)
df['dscc_dif'] = np.exp(df.dscc_am) - np.exp(df.dscc_pm)

df['tu_uc'] = df.tu_dif / np.exp(df.tu_am)
df['dscc_uc'] = df.dscc_dif / np.exp(df.dscc_am)


df

In [ ]:
df = pd.DataFrame()
df['dscc_am'] = dscc.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['tu_am'] = si_tu.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['dscc_pm'] = dscc.direct_normal_irradiation.langley_pm.langley_fitres.intercept
df['tu_pm'] = si_tu.direct_normal_irradiation.langley_pm.langley_fitres.intercept

# df['tu_ratio'] = df.tu_am/df.tu_pm
# df['tu_dif'] = df.tu_am - df.tu_pm
# df['dscc_dif'] = df.dscc_am - df.dscc_pm

df['tu_dif'] = np.exp(df.tu_am) - np.exp(df.tu_pm)
df['dscc_dif'] = np.exp(df.dscc_am) - np.exp(df.dscc_pm)

df['tu_uc'] = df.tu_dif / np.exp(df.tu_am)
df['dscc_uc'] = df.dscc_dif / np.exp(df.dscc_am)


df

In [ ]:
np.exp(df.tu_am)

In [ ]:
df = pd.DataFrame()
df['dscc_am'] = dscc.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['tu_am'] = si_tu.direct_normal_irradiation.langley_am.langley_fitres.intercept
df['dscc_pm'] = dscc.direct_normal_irradiation.langley_pm.langley_fitres.intercept
df['tu_pm'] = si_tu.direct_normal_irradiation.langley_pm.langley_fitres.intercept
# df['tu_ratio'] = df.tu_am/df.tu_pm
df['tu_dif'] = df.tu_am - df.tu_pm
df['dscc_dif'] = df.dscc_am - df.dscc_pm

df

# how much does a cosine change?

In [ ]:
p2fld = pl.Path('.')
p2fl = list(p2fld.glob('*.cos'))

In [ ]:
reload(atmcf)

In [ ]:
cals = []
for p2f in p2fl:
    print(p2f)
    out = atmcf.read_mfrsr_cal_cos(p2f)
    cals.append(out)
    # break

In [ ]:
cals = sorted(cals, key = lambda cal: pd.to_datetime([c for c in cal.header.split('\n') if 'Test_date' in c][0].split('\t')[1]).year)

In [ ]:
f,a = plt.subplots()
wl = 415
for cal in cals:
    dt = pd.to_datetime([c for c in cal.header.split('\n') if 'Test_date' in c][0].split('\t')[1]).year
    cal.spectral_NS.sel(channel = wl).plot(ax = a, label = dt)
a.axhline(1, color = 'black', ls = '--')
a.set_ylim(0.9,1.1)
a.legend()

# Compare to what Gary uses

In [ ]:
Gary

In [ ]:
dssol = sol_parser.read_sol_to_xarray('tbl_mfrsr_20221103_D824_3126_660.sol')

In [ ]:
f,a = plt.subplots()
cal = cals[1]
# dssol.SN.sel(channel = 2).plot(ax = a)
a.plot(-dssol.angle, dssol.SN.sel(channel = 2))
wl = 415
cal.spectral_NS.sel(channel = wl).plot(ax = a, label = dt)
a.set_ylim(0.9,1.1)

In [ ]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.cal_facility.lab as atmcal

In [ ]:
reload(atmcal)

In [ ]:
dscos = atmcal.read_mfrsr_cal_cos('/Volumes/grad/Calibration_facilities/cucf/NOAA_GRAD_VisMFRSRs/V0660/Reported/V0660_20221109.cos')

In [ ]:
dssol = atmcal.read_factory_cal_sol('tbl_mfrsr_20221103_D824_3126_660.sol')

In [ ]:
f,a = plt.subplots()
wl = 1625
dssol.spectral_EW.sel(channel=wl).plot.line(x = 'angle', ax = a)
dscos.spectral_EW.sel(channel=wl).plot.line(x = 'angle', ax = a, color = 'black')
a.set_ylim(0.9,1.1)

In [ ]:
f,a = plt.subplots()
wl = 1625
dssol.spectral_NS.sel(channel=wl).plot.line(x = 'angle', ax = a)
dscos.spectral_NS.sel(channel=wl).plot.line(x = 'angle', ax = a, color = 'black')
a.set_ylim(0.9,1.1)

In [ ]:
f,a = plt.subplots()
dssol.broadband_EW.plot(ax = a)
dscos.broadband_EW.plot(ax = a)

In [ ]:
f,a = plt.subplots()
dssol.broadband_NS.plot(ax = a)
dscos.broadband_NS.plot(ax = a)

In [ ]:
dscos

# plot for testing

In [ ]:

na = 500
nz = 500
coord_az = np.linspace(0,360, na)
coord_ze = np.linspace(0,90, nz)
# az, ze = np.meshgrid(coord_az, coord_ze)

In [ ]:
dat = dspol.spectral.interp({'azimuth': coord_az, 'zenith': coord_ze})
# dat

In [ ]:
dat.sel(channel = wl).plot(cmap = plt.cm.gnuplot2, vmin = 0.85)#norm = 'log')