# Todo

[ ] how to only process the last 2 years of data to speed things up
[ ] implement the below into a script
[ ] put the script on pulsar and run in cronjob

# Objective
Here we convert the the raw mfrsr data into netcdf files. In the process data is chopped into daily files. Note, no additional actions are take. It is not recommended to use sun positions here.

# New: inplement the new WorkplanerDaily

In [37]:
import surfradpy.products.mfr_raw2netcdf as srfr2nc

In [38]:
import surfradpy.scripts.surfrad_mfrsr_raw2netcdf as srfscpt

In [39]:
reload(srfscpt)

In [40]:
out = srfscpt.run(prefix='/Volumes/', log_folder='/Users/htelg/.processlogs/', verbose = False)

start time: 2026-05-13 09:19:02.572074
inl

inl workplan.shape: (1, 3)

.bnd

bnd workplan.shape: (1, 3)

.dra

dra workplan.shape: (1, 3)

.gwn

gwn workplan.shape: (1, 3)

.psu

psu workplan.shape: (1, 3)

.sxf

sxf workplan.shape: (1, 3)

.tbl

tbl workplan.shape: (1, 3)

.fpe

fpe workplan.shape: (1, 3)

.number of cleanes: 16
number of errors: 0
number of warnings: 0
time finished: 2026-05-13 09:19:16.783078
total processing time: 0.003947501111111111 hours

In [41]:
out['product_instance'].workplan

,p2f_in,p2f_out,day_complete
2026-05-13,[/Volumes/grad/Inst/MFR/SURFRAD/fpe/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/fpe/mfrsr/raw.n...,False

In [42]:
reload(srfr2nc)
reload(srfr2nc.prowo)
reload(srfr2nc.prowo.prodlab)

# This are the internals of the script

In [43]:
import surfradpy.products.mfr_raw2netcdf as mfr_r2nc
import surfradpy.database as sfp_db
import productomator.lab as prolab

In [44]:
path = pl.Path('../../../databases/surfrad_database.db')
prefix = '/Volumes/grad'

In [45]:
reporter = prolab.Reporter('surfrad_mfr_raw2netcdf', 
                             log_folder='/Users/htelg/.processlogs/',
                             reporting_frequency=(6, 'h'),
                          )


sites = ['inl',
         #'bnd',
#           'dra',
#          'gwn',
#          'psu', 
#          'sxf',
         # 'tbl',
         # 'fpe',
]

end = pd.Timestamp.now()
start = end - pd.to_timedelta(60, 'D')

# end = pd.to_datetime('2026-01-31')
# start = pd.to_datetime('2026-01-27')

start time: 2026-05-13 09:19:16.908840

In [46]:
reload(mfr_r2nc)
reload(sfp_db)

In [47]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.surfrad.surfrad as atmsrf

In [48]:
for site in sites:
    print(site)
    path_in = f'{prefix}/Inst/MFR/SURFRAD/{site}/mfrsr/raw/'
    
    siteinst = atmsrf.network.stations.find_site(site)
    time_offset = pd.to_timedelta(- siteinst.time_zone['diff2UTC_of_standard_time'], 'h')
    ci = mfr_r2nc.MfrsrRawToNetcdf(path_in,
                                  # f'{prefix}/Inst/MFR/SURFRAD/{site}/mfrsr/raw.netcdf/v{{version}}/',
                                  f'{prefix}/Inst/MFR/SURFRAD/{{site}}/mfrsr/raw.netcdf/v{{version}}',
                                  # date_from_name = lambda name: pd.to_datetime(' '.join(name.split('.')[0].split('_')[-2:])) + time_offset,                       
                                  # glob_pattern_raw=f'[{dt.year - 1},{dt.year}]/*.xmd',
                                  # glob_pattern_raw='202[56]/*.xmd',
                                  glob_pattern_raw='*.xmd',
                                   start = start,
                                   end = end,
                                  # verbose = True,
                                  site = siteinst,
                                  path2surfrad_database  = '../../../databases/surfrad_database.db',
                                   reporter = reporter,
                              )
    self = ci

inl

AssertionError: No result for inl

In [ ]:
atmsrf.network.stations.find_site(site)

In [ ]:
siteinst

In [ ]:
self.workplan

Get all files in /Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw with "files_between" function and start: 2026-03-06 16:05:42.720746, end: 2026-05-05 16:05:42.720746 and glob pattern: *.xmd

,p2f_in,p2f_out,day_complete
2026-03-06,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-03-07,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-03-08,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-03-09,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-03-10,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
...,...,...,...
2026-05-01,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-05-02,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-05-03,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-05-04,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,True
2026-05-05,[/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/...,/Volumes/grad/Inst/MFR/SURFRAD/Station(Table M...,False

In [ ]:
self.workplan.iloc[-1].p2f_in

[PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_163108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_173108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_183106.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_193101.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_203051.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_213050.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_223056.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260504_233049.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_003051.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_013050.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_023050.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_033050.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_043050.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_053102.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_063105.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_073108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_083108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_093108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_103108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_113108.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_123109.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_133106.xmd'),
 PosixPath('/Volumes/grad/Inst/MFR/SURFRAD/tbl/mfrsr/raw/2026/tbl_mfrsr_20260505_143108.xmd')]

In [ ]:
oldwp = self.workplan.copy()

In [ ]:
oldwp.iloc[-1].p2f_in

In [ ]:
    # ci.workplan = ci.workplan[::-1]
    print(f'{site} workplan.shape: {ci.workplan.shape}')
    # ci.masterplan['processed_files'].iloc[0].p2out
    # ci.masterplan['raw_files'].iloc[0].p2f_in
    # ci.workplan
    if 1:
        out = ci.process(verbose=True, save=False, justone = False)
        break
    else:
        out = ci.process(verbose=True)

reporter.wrapup()

## Why do those gaps appear

In [ ]:
import surfradpy.mfr_raw2netcdf as mfr_r2nc
import surfradpy.database as sfp_db
import productomator.lab as prolab

In [ ]:
reload(mfr_r2nc)
reload(sfp_db)

In [ ]:
path = pl.Path('../../../databases/surfrad_database.db')
prefix = '/Volumes/grad'

In [ ]:
reporter = prolab.Reporter('surfrad_mfr_raw2netcdf', 
                             log_folder='/Users/htelg/.processlogs/',
                             reporting_frequency=(6, 'h'),
                          )


# sites = [
         #'bnd',
#           'dra',
#          'gwn',
#          'psu', 
#          'sxf',
site =  'tbl'
         # 'fpe',
# ]

# end = pd.Timestamp.now()
# start = start - pd.to_timedelta(60, 'D')

end = pd.to_datetime('2026-01-31')
start = pd.to_datetime('2026-01-27')
for i in range(18):
    print(f'idx: {i}')
    path_in = f'{prefix}/Inst/MFR/SURFRAD/{site}/mfrsr/raw/'
    ci = mfr_r2nc.MfrsrRawToNetcdf(path_in,
                                  # f'{prefix}/Inst/MFR/SURFRAD/{site}/mfrsr/raw.netcdf/v{{version}}/',
                                  f'~/tmp/raw2netcdf/{site}/mfrsr/raw.netcdf/v{{version}}/',
                                  '{year}/{site}_mfrsr_raw_{year}{month}{day}.nc',
                                  # glob_pattern_raw=f'[{dt.year - 1},{dt.year}]/*.xmd',
                                  # glob_pattern_raw='202[56]/*.xmd',
                                  glob_pattern_raw='*.xmd',
                                   start = start,
                                   end = end,
                                  # verbose = True,
                                  site = site,
                                  path2surfrad_database  = '../../../databases/surfrad_database.db',
                                   reporter = reporter,
                              )
    self = ci
    if i!=0:
        if np.all(ci.workplan == old_wp):
            i+=1
    old_wp = ci.workplan.copy()
    ci.workplan = ci.workplan.iloc[:(i+1)]
    # print(ci.workplan)
    # ci.workplan = ci.workplan[::-1]
    # print(f'{site} workplan.shape: {ci.workplan.shape}')
    # ci.masterplan['processed_files'].iloc[0].p2out
    # ci.masterplan['raw_files'].iloc[0].p2f_in
    # ci.workplan
    if 0:
        out = ci.process(verbose=True, save=False, justone = False)
        break
    else:
        out = ci.process(verbose=True)

reporter.wrapup()

In [ ]:
ci.masterplan['raw_files']

In [ ]:
np.all(ci.workplan == old_wp)

In [ ]:
ci.workplan

In [ ]:
version = '0.3'
days = 7
# p2fld = '/Volumes/grad/Inst/MFR/SURFRAD/bnd/mfrsr/raw.netcdf/v0.3/2026/
# p2fld = '/Volumes/grad/Inst/MFR/SURFRAD/bnd/mfrsr/v0.3/2026/
p2fld = f'~/tmp/raw2netcdf/{site}/mfrsr/raw.netcdf/v{{version}}/2026'

In [ ]:
pl.Path(p2fld.format(site = s, version = version))

In [ ]:
sites = [
    # 'gwn', 'psu', 
         # 'sxf', 
         'tbl', 
    # 'bnd', 'fpe', 'dra'
        ]
data = {}
for s in sites:
    # print(s)
    fl = list(pl.Path(p2fld.format(site = s, version = version)).expanduser().glob('*.nc'))
    fl.sort()
    
    fl[- days:]
    
    ds = xr.open_mfdataset(fl[- days:])
    
    data[s] = ds

In [ ]:
f, aa = plt.subplots(len(data.keys()), sharex=True, gridspec_kw={'hspace': 0})
aa = [aa,]
for e,s in enumerate(data):
    a = aa[e]
    ds  = data[s]
    ds.alltime.plot.line(x='datetime', ax = a, lw = 1)
    a.legend().remove()
    a.text(0.05, 0.9, s, transform = a.transAxes)

end = pd.Timestamp.now(tz = 'UTC')
start = end - pd.to_timedelta(days, 'D')
# aa[-1].set_xlim(start, end)

# Next: during processing collect all the metadata and confirm match between available information from filename and content