# surfrad database interface

This database contains information about things that do not change all that frequently:

- instrument deployment
- instrument inventory

QC related databases, which change quit frequently,0 are disconnected to tis database as long as we are not having a central server that prevents simultanius writing.

mention to handle (store, performe operations, and return) data in xarry objects (Dataset, DataArray). Only use pandas if operation or equivalent perfomrance is not available in xarry objects. Use numpy arrays only if pandas ojects do not meet the requirements.

# Overview

## initiate a database instance and get a snapshot

In [68]:
import surfradpy.database as srfdb

In [79]:
reload(srfdb)

In [80]:
p2db = 'surfrad_database.db'
db = srfdb.SurfradDatabase(p2db)

In [53]:
sps = db.snapshot()

In [54]:
sps.keys()

dict_keys(['tables', 'schema', 'preview'])

In [55]:
sps['tables']

['instrument_type',
 'channels_wl',
 'clearsky_fits',
 'sqlite_sequence',
 'sites',
 'instruments_mfrsr',
 'deployments',
 'audit_log']

## Recent changes

In [65]:
db.dump_table('audit_log')

,time_of_execution,function,args,user
0,2026-06-05T17:32:56.013236+00:00,SurfradDatabase.remove_table,"{""args"": [""audit_log""], ""kwargs"": {}}",htelg
1,2026-06-05T17:33:01.647857+00:00,SurfradDatabase.add_table,"{""args"": [""test""], ""kwargs"": {}}",htelg

# Tabels

## basic table obs

In [57]:
sps = db.snapshot()
sps['tables']

['instrument_type',
 'channels_wl',
 'clearsky_fits',
 'sqlite_sequence',
 'sites',
 'instruments_mfrsr',
 'deployments',
 'audit_log']

In [ ]:
db.add_table('test')

In [61]:
db.remove_table('test')

## Sites

In [83]:
db.dump_table('sites')

### add a site

In [8]:
site = {
    "abb": "ABC",
    "name": "Example Site",
    "elevation": 1520.5,
    "latitude": 46.807251,
    "longitude": 9.838257,
    "network": "MyNetwork",
    "country": "US"
}

In [9]:
db.add_site(**site)

### delete a site

In [10]:
db.find_site_info(abb = 'ABC')

index                  10
site_id                 9
abb                   ABC
name         Example Site
elevation          1520.5
latitude          39.7392
longitude       -104.9903
network         MyNetwork
Name: 0, dtype: object

In [11]:
db.remove_site(abb = 'ABC')

## Deployments

In [85]:
db.dump_table('deployments')

,index,Date_start,Date_stop,Location,instrument_type_id,instrument_type,instrument_sn,facing
0,0,2014-06-23 00:00:00,2014-08-20 00:00:00,bao,1,mfrsr,453,unk
1,1,2014-09-15 00:00:00,NaN,ska,1,mfrsr,453,unk
2,2,2016-04-22 00:00:00,2018-10-15 00:00:00,mlo,1,mfrsr,453,unk
3,3,2018-10-16 00:00:00,NaN,cucf,1,mfrsr,453,unk
4,4,2020-03-12 00:00:00,2020-03-24 00:00:00,ska?,1,mfrsr,453,unk
...,...,...,...,...,...,...,...,...
274,4,2021-08-01 00:00:00,NaN,yes,1,mfrsr,688,unk
275,0,2020-12-15 00:00:00,NaN,2d401,1,mfrsr,689,unk
276,1,2021-03-01 00:00:00,2021-03-15 00:00:00,cucf,1,mfrsr,689,unk
277,3,2021-10-01 00:00:00,planned,kettle-ponds,1,mfrsr,689,unk
278,4,2021-08-01 00:00:00,NaN,yes,1,mfrsr,689,unk

# update sites table (this should no longer be necessary)

In [ ]:
import atmPy.data_archives.NOAA_ESRL_GMD_GRAD.surfrad.surfrad as atmsrf

In [ ]:
reload(atmsrf)

In [ ]:
overwrite = True

In [ ]:
df = db.dump_table('sites')
df = df.drop('index', axis=1)
df

In [ ]:
# df = df.sort_values('site_id')

In [ ]:
# create the table
####
for site in atmsrf._locations:
    # print(site)
    abb = site['abbreviation'][0].lower()
    print(abb)
    if (df.abb == abb).sum() > 0:
        if not overwrite:
            print(f'{abb} already in table ... skip')
            continue
        else:
            exists = df[df.abb == abb].iloc[0]
            site_id = exists.site_id
            index = exists.name
            df = df.drop(index)
    else:
        site_id  = df.site_id.max() + 1
        index = df.index.max() + 1
        
    
    row = dict(site_id = site_id,
               abb = abb,
               name = site['name'],
               network = 'surfrad',
               elevation = site['alt'],
               latitude = site['lat'],
               longitude = site['lon'],
              )
    row
         
    
    df = pd.concat([df,pd.DataFrame(row, index=[index])])

    ######
    # below are the cases where there are alternative names

    if row['abb'] == 'bnd':
        # first remove if they exist already
        abbalt = 'bon'
        df.drop(df[df.abb == abbalt].index, inplace = True)
        row['abb'] = abbalt
        df = pd.concat([df,pd.DataFrame(row, index=[index])])
    if row['abb'] == 'fpk':
        # row['abb'] = 'fpe'
        abbalt = 'fpe'
        df.drop(df[df.abb == abbalt].index, inplace = True)
        row['abb'] = abbalt
        df = pd.concat([df,pd.DataFrame(row, index=[index])])

df = df.sort_values('site_id')

In [ ]:
df

In [ ]:
# save into database
#####
if 0:
    with sqlite3.connect(db.path2db) as dbt:
        df.to_sql('sites', dbt, if_exists='replace')

# update MFRSR_History

first download the most up-to-date MFRSR_History file from [here](https://docs.google.com/spreadsheets/d/1pzBw4ZPxWhRVg-wM69hxUEOcbjFAc42nzZ9czwYdl-c/edit?gid=1879435883#gid=1879435883)

In [1]:
import surfradpy.database as srfdb

In [2]:
reload(srfdb)

In [3]:
p2db = 'surfrad_database.db'
db = srfdb.SurfradDatabase(p2db)

In [4]:
out = db.update_mfrsr_history('MFRSR_History.xlsx', 
                              replace=True,
                              # dryrun=True
                             )

Instrument 451 has fist column with the name Purchased SN 451 w/stand from eBay July 2024 not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 607 has fist column with the name Brookhaven MFRSR not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 559 has fist column with the name Thermopile MFRSR (Standard filters) not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?
Instrument 584 has fist column with the name MFRSR purchased around 2013 not "Date_start" as expected. This indicates that the instrument was never put into action ... bought for spare parts?

In [ ]:
db.

In [ ]:
dft = db.tp_df.iloc[[0]]

In [ ]:
dft.Date_start

In [ ]:
dft.Date_start.dtypes.name == 'datetime64[us]'

In [ ]:
plt = None

In [ ]:
from atmPy.opt_imports import OptionalImport

In [ ]:
mpl = OptionalImport('matplotlib')

In [ ]:
mpl

In [ ]:
plt = OptionalImport('matplotlib.pyplot')

In [ ]:
plt.plot()

In [ ]:
__import__('matplotlib.pyplot')

In [ ]:
import importlib

In [ ]:
plt = importlib.import_module('matplotlib.pyplot')

In [ ]:
plt.plot()

# Execute random queries

In [ ]:
df = db.execute_query('SELECT * FROM sites WHERE network = "surfrad"')
df